
modLoader="javafml"
loaderVersion="[43,)"
license="CC0 1.0 Universal"

[[mods]]
modId="applecrates_compat"
version='${file.jarVersion}'
displayName="AppleCrates Compat"
#logoFile="applecrates_compat.png" #optional
credits = "Original Author is AbsolemJackdaw, all credit goes to them. I'm just maintaining the code for this since my family still uses the mod."
authors = "Warren Tode (ToadieOdie)"
description="Just a compatibility mod I forked and continue to keep running and I will try to keep it working as best as I can for as long as I can."

[[dependencies.applecrates_compat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.applecrates_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.applecrates_compat]]
    modId = "applecrates"
    mandatory = true
    versionRange = "[1.19.2-2.9.0,)"
    ordering = "BEFORE"
    side = "BOTH"