modLoader="javafml"
loaderVersion="[43,)"
license="CC0 1.0 Universal"
issueTrackerURL="https://github.com/warrentode/AppleCratesCompat/issues"

[[mods]]
modId="applecrates_compat"
version='${file.jarVersion}'
displayName="AppleCrates Compat"
updateJSONURL = "https://www.planetminecraft.com/mod/applecratescompat/"
displayURL = "https://www.planetminecraft.com/mod/applecratescompat/"
#logoFile="applecrates_compat.png" #optional
credits = "Original Author is AbsolemJackdaw, all credit goes to them. I'm just maintaining the code for this since my family still uses the mod."
authors = "Warren Tode (ToadieOdie)"
description="Just a compatibility mod I forked and continue to keep running and I will try to keep it working as best as I can for as long as I can."

[[dependencies.applecrates_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.applecrates_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.applecrates_compat]]
    modId = "applecrates"
    mandatory = true
    versionRange = "[3.1.0,)"
    ordering = "BEFORE"
    side = "BOTH"